// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\a6.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: a6
// Source Path: FP_sub/fp model/IIR_section_1/a6
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module a6
          (c);


  output  signed [14:0] c;  // sfix15_En11


  wire signed [14:0] a6_out1;  // sfix15_En11


  assign a6_out1 = 15'sb101010010110000;



  assign c = a6_out1;

endmodule  // a6

