vlib work
vlog  fp_model_tc.v
vlog  b0_1.v
vlog  b0_2.v
vlog  b2_1.v
vlog  b2_2.v
vlog  b4_1.v
vlog  b4_2.v
vlog  b6.v
vlog  multb0_1.v
vlog  multb0_2.v
vlog  multb2_1.v
vlog  multb2_2.v
vlog  multb4_1.v
vlog  multb4_2.v
vlog  multb6.v
vlog  sumb10_1.v
vlog  sumb12_1.v
vlog  sumb2_1.v
vlog  sumb4_1.v
vlog  sumb6_1.v
vlog  sumb8_1.v
vlog  FIR_section_1.v
vlog  b0_1_block.v
vlog  b0_2_block.v
vlog  b2_1_block.v
vlog  b2_2_block.v
vlog  b4_1_block.v
vlog  b4_2_block.v
vlog  b6_block.v
vlog  multb0_1_block.v
vlog  multb0_2_block.v
vlog  multb2_1_block.v
vlog  multb2_2_block.v
vlog  multb4_1_block.v
vlog  multb4_2_block.v
vlog  multb6_block.v
vlog  sumb10_1_block.v
vlog  sumb12_1_block.v
vlog  sumb2_1_block.v
vlog  sumb4_1_block.v
vlog  sumb6_1_block.v
vlog  sumb8_1_block.v
vlog  FIR_section_2.v
vlog  b0_1_block1.v
vlog  b0_2_block1.v
vlog  b2_1_block1.v
vlog  b2_2_block1.v
vlog  b4_1_block1.v
vlog  b4_2_block1.v
vlog  b6_block1.v
vlog  multb0_1_block1.v
vlog  multb0_2_block1.v
vlog  multb2_1_block1.v
vlog  multb2_2_block1.v
vlog  multb4_1_block1.v
vlog  multb4_2_block1.v
vlog  multb6_block1.v
vlog  sumb10_1_block1.v
vlog  sumb12_1_block1.v
vlog  sumb2_1_block1.v
vlog  sumb4_1_block1.v
vlog  sumb6_1_block1.v
vlog  sumb8_1_block1.v
vlog  FIR_section_3.v
vlog  a10.v
vlog  a12.v
vlog  a2.v
vlog  a4.v
vlog  a6.v
vlog  a8.v
vlog  multa10.v
vlog  multa12.v
vlog  multa2.v
vlog  multa4.v
vlog  multa6.v
vlog  multa8.v
vlog  suma2.v
vlog  suma4.v
vlog  suma6.v
vlog  sumd.v
vlog  sumin.v
vlog  sumq.v
vlog  IIR_section_1.v
vlog  a10_block.v
vlog  a12_block.v
vlog  a2_block.v
vlog  a4_block.v
vlog  a6_block.v
vlog  a8_block.v
vlog  multa10_block.v
vlog  multa12_block.v
vlog  multa2_block.v
vlog  multa4_block.v
vlog  multa6_block.v
vlog  multa8_block.v
vlog  suma2_block.v
vlog  suma4_block.v
vlog  suma6_block.v
vlog  sumd_block.v
vlog  sumin_block.v
vlog  sumq_block.v
vlog  IIR_section_2.v
vlog  a10_block1.v
vlog  a12_block1.v
vlog  a2_block1.v
vlog  a4_block1.v
vlog  a6_block1.v
vlog  a8_block1.v
vlog  multa10_block1.v
vlog  multa12_block1.v
vlog  multa2_block1.v
vlog  multa4_block1.v
vlog  multa6_block1.v
vlog  multa8_block1.v
vlog  suma2_block1.v
vlog  suma4_block1.v
vlog  suma6_block1.v
vlog  sumd_block1.v
vlog  sumin_block1.v
vlog  sumq_block1.v
vlog  IIR_section_3.v
vlog  OUT_MUX.v
vlog  Z1toZ3_1.v
vlog  Z1toZ3_2.v
vlog  Z1toZ3_3.v
vlog  fp_model.v
