// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\multa12_block.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multa12_block
// Source Path: FP_sub/fp model/IIR_section_2/multa12
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multa12_block
          (In2,
           In1,
           Out1);


  input   signed [14:0] In2;  // sfix15_En11
  input   signed [35:0] In1;  // sfix36_En27
  output  signed [26:0] Out1;  // sfix27_En19


  wire signed [50:0] multa12_mul_temp;  // sfix51_En38
  wire signed [26:0] multa12_out1;  // sfix27_En19


  assign multa12_mul_temp = In1 * In2;
  assign multa12_out1 = (((multa12_mul_temp[50] == 1'b0) && (multa12_mul_temp[49:45] != 5'b00000)) || ((multa12_mul_temp[50] == 1'b0) && (multa12_mul_temp[45:19] == 27'sb011111111111111111111111111)) ? 27'sb011111111111111111111111111 :
              ((multa12_mul_temp[50] == 1'b1) && (multa12_mul_temp[49:45] != 5'b11111) ? 27'sb100000000000000000000000000 :
              multa12_mul_temp[45:19] + $signed({1'b0, multa12_mul_temp[18]})));



  assign Out1 = multa12_out1;

endmodule  // multa12_block

