// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\multb0_1_block.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multb0_1_block
// Source Path: FP_sub/fp model/FIR_section_2/multb0_1
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multb0_1_block
          (In2,
           In1,
           Out1);


  input   signed [11:0] In2;  // sfix12_En11
  input   signed [10:0] In1;  // sfix11_En3
  output  signed [21:0] Out1;  // sfix22_En14


  wire signed [22:0] multb0_mul_temp;  // sfix23_En14
  wire signed [21:0] multb0_out1;  // sfix22_En14


  assign multb0_mul_temp = In1 * In2;
  assign multb0_out1 = ((multb0_mul_temp[22] == 1'b0) && (multb0_mul_temp[21] != 1'b0) ? 22'sb0111111111111111111111 :
              ((multb0_mul_temp[22] == 1'b1) && (multb0_mul_temp[21] != 1'b1) ? 22'sb1000000000000000000000 :
              $signed(multb0_mul_temp[21:0])));



  assign Out1 = multb0_out1;

endmodule  // multb0_1_block

