// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\multa2.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multa2
// Source Path: FP_sub/fp model/IIR_section_1/multa2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multa2
          (In2,
           In1,
           Out1);


  input   signed [14:0] In2;  // sfix15_En11
  input   signed [35:0] In1;  // sfix36_En27
  output  signed [38:0] Out1;  // sfix39_En29


  wire signed [50:0] multa2_mul_temp;  // sfix51_En38
  wire signed [38:0] multa2_out1;  // sfix39_En29


  assign multa2_mul_temp = In1 * In2;
  assign multa2_out1 = (((multa2_mul_temp[50] == 1'b0) && (multa2_mul_temp[49:47] != 3'b000)) || ((multa2_mul_temp[50] == 1'b0) && (multa2_mul_temp[47:9] == 39'sh3FFFFFFFFF)) ? 39'sh3FFFFFFFFF :
              ((multa2_mul_temp[50] == 1'b1) && (multa2_mul_temp[49:47] != 3'b111) ? 39'sh4000000000 :
              multa2_mul_temp[47:9] + $signed({1'b0, multa2_mul_temp[8]})));



  assign Out1 = multa2_out1;

endmodule  // multa2

