// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\multa10_block1.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multa10_block1
// Source Path: FP_sub/fp model/IIR_section_3/multa10
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multa10_block1
          (In2,
           In1,
           Out1);


  input   signed [14:0] In2;  // sfix15_En11
  input   signed [35:0] In1;  // sfix36_En27
  output  signed [25:0] Out1;  // sfix26_En17


  wire signed [50:0] multa10_mul_temp;  // sfix51_En38
  wire signed [25:0] multa10_out1;  // sfix26_En17


  assign multa10_mul_temp = In1 * In2;
  assign multa10_out1 = (((multa10_mul_temp[50] == 1'b0) && (multa10_mul_temp[49:46] != 4'b0000)) || ((multa10_mul_temp[50] == 1'b0) && (multa10_mul_temp[46:21] == 26'sb01111111111111111111111111)) ? 26'sb01111111111111111111111111 :
              ((multa10_mul_temp[50] == 1'b1) && (multa10_mul_temp[49:46] != 4'b1111) ? 26'sb10000000000000000000000000 :
              multa10_mul_temp[46:21] + $signed({1'b0, multa10_mul_temp[20]})));



  assign Out1 = multa10_out1;

endmodule  // multa10_block1

