// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\suma2.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: suma2
// Source Path: FP_sub/fp model/IIR_section_1/suma2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module suma2
          (In2,
           In1,
           Out1);


  input   signed [38:0] In2;  // sfix39_En29
  input   signed [35:0] In1;  // sfix36_En26
  output  signed [32:0] Out1;  // sfix33_En22


  wire signed [32:0] suma2_add_cast;  // sfix33_En22
  wire signed [32:0] suma2_add_cast_1;  // sfix33_En22
  wire signed [32:0] suma2_out1;  // sfix33_En22


  assign suma2_add_cast = ({In1[35], In1[35:4]}) + $signed({1'b0, In1[3]});
  assign suma2_add_cast_1 = ({In2[38], In2[38:7]}) + $signed({1'b0, In2[6]});
  assign suma2_out1 = suma2_add_cast + suma2_add_cast_1;



  assign Out1 = suma2_out1;

endmodule  // suma2

