// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\suma4_block.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: suma4_block
// Source Path: FP_sub/fp model/IIR_section_2/suma4
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module suma4_block
          (In1,
           In2,
           Out1);


  input   signed [43:0] In1;  // sfix44_En33
  input   signed [25:0] In2;  // sfix26_En17
  output  signed [41:0] Out1;  // sfix42_En31


  wire signed [41:0] suma4_add_cast;  // sfix42_En31
  wire signed [42:0] suma4_add_cast_1;  // sfix43_En31
  wire signed [41:0] suma4_add_cast_2;  // sfix42_En31
  wire signed [42:0] suma4_add_cast_3;  // sfix43_En31
  wire signed [42:0] suma4_add_temp;  // sfix43_En31
  wire signed [41:0] suma4_out1;  // sfix42_En31


  assign suma4_add_cast = ((In1[43] == 1'b0) && (In1[42:2] == 41'h1FFFFFFFFFF) ? 42'sh1FFFFFFFFFF :
              In1[43:2] + $signed({1'b0, In1[1]}));
  assign suma4_add_cast_1 = {suma4_add_cast[41], suma4_add_cast};
  assign suma4_add_cast_2 = {{2{In2[25]}}, {In2, 14'b00000000000000}};
  assign suma4_add_cast_3 = {suma4_add_cast_2[41], suma4_add_cast_2};
  assign suma4_add_temp = suma4_add_cast_1 + suma4_add_cast_3;
  assign suma4_out1 = ((suma4_add_temp[42] == 1'b0) && (suma4_add_temp[41] != 1'b0) ? 42'sh1FFFFFFFFFF :
              ((suma4_add_temp[42] == 1'b1) && (suma4_add_temp[41] != 1'b1) ? 42'sh20000000000 :
              $signed(suma4_add_temp[41:0])));



  assign Out1 = suma4_out1;

endmodule  // suma4_block

