// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\multa8.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: multa8
// Source Path: FP_sub/fp model/IIR_section_1/multa8
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module multa8
          (In2,
           In1,
           Out1);


  input   signed [14:0] In2;  // sfix15_En11
  input   signed [35:0] In1;  // sfix36_En27
  output  signed [35:0] Out1;  // sfix36_En26


  wire signed [50:0] multa8_mul_temp;  // sfix51_En38
  wire signed [35:0] multa8_out1;  // sfix36_En26


  assign multa8_mul_temp = In1 * In2;
  assign multa8_out1 = (((multa8_mul_temp[50] == 1'b0) && (multa8_mul_temp[49:47] != 3'b000)) || ((multa8_mul_temp[50] == 1'b0) && (multa8_mul_temp[47:12] == 36'sh7FFFFFFFF)) ? 36'sh7FFFFFFFF :
              ((multa8_mul_temp[50] == 1'b1) && (multa8_mul_temp[49:47] != 3'b111) ? 36'sh800000000 :
              multa8_mul_temp[47:12] + $signed({1'b0, multa8_mul_temp[11]})));



  assign Out1 = multa8_out1;

endmodule  // multa8

