// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\a2.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: a2
// Source Path: FP_sub/fp model/IIR_section_1/a2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module a2
          (c);


  output  signed [14:0] c;  // sfix15_En11


  wire signed [14:0] a2_out1;  // sfix15_En11


  assign a2_out1 = 15'sb110010110101011;



  assign c = a2_out1;

endmodule  // a2

