// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\a8_block.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: a8_block
// Source Path: FP_sub/fp model/IIR_section_2/a8
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module a8_block
          (c);


  output  signed [14:0] c;  // sfix15_En11


  wire signed [14:0] a8_out1;  // sfix15_En11


  assign a8_out1 = 15'sb110010100101010;



  assign c = a8_out1;

endmodule  // a8_block

