// -------------------------------------------------------------
// 
// File Name: D:\WorkSpace\LabWorks\DSP_SIMULINK\SL_to_SV\Filter\SV\FP_sub\b4_2_block.v
// Created: 2023-10-12 14:13:41
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: b4_2_block
// Source Path: FP_sub/fp model/FIR_section_2/b4_2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module b4_2_block
          (c);


  output  signed [11:0] c;  // sfix12_En11


  wire signed [11:0] b4_out1;  // sfix12_En11


  assign b4_out1 = 12'sb000000100110;



  assign c = b4_out1;

endmodule  // b4_2_block

